apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      containers:
      - name: mysql-exporter
        image: prom/mysqld-exporter
        ports:
        - containerPort: 9104
        env:
        - name: DATA_SOURCE_NAME
          value: "<mysql-user>:<mysql-password>@(localhost:3306)/"
